### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Steditor** [acigna/jquery-ajax-native#1]
Thanks for this jquery ajax plugin! It would be great if you could add a `package.json` and publish it to [npm](http://npmjs.com)!

**Comment by tarikbenmerar** [comment]
@Steditor done. Thank you for that, and sorry for my late response :( being so busy these days. Could you tell me how are you using it ? I am so interrested in its usage.

**Comment by Steditor** [comment]
We want to use it in our web app that combines 3D printing and lego bricks (https://brickify.it and http://github.com/brickify/brickify) when we generate the lego building instructions. As a part of that we download images of the needed bricks from the server and provide the download as zip file - therefore an `arraybuffer` ist needed. Currently we use `XMLHttpRequest` [directly](https://github.com/brickify/brickify/blob/develop/src/plugins/legoInstructions/LegoInstructions.coffee#L242), but we will switch to `jquery-ajax-native` soon, now it's published!

**Comment by tarikbenmerar** [comment]
@Steditor wonderful !!! Good luck for the project. Please, keep me updated when you integrate the library ;).
