### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by s0By** [acigna/jquery-ajax-native#3]
Hi guys.

Probably a stupid question, but I can't seem to include properly this script using webpack...
I mean, I can include it without any problem, but after building the bundle ajax doesn't see the script.

How to make it work? Is there a tricky way to include it?

**Comment by tarikbenmerar** [comment]
Hi @s0By,

Sorry for my late response. I personnaly didn't test it with webpack. Can you give me more details about the issue ? How are you using it with webpack.

Thanks again,

**Comment by s0By** [comment]
My webpack.config.js looks like this:
```
var webpack = require('webpack');
var ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
    entry: {
        vendor: "./vendor.js"
    },
    output: {
        path: __dirname + "/public/assets/vendor",
        filename: "[name].min.js"
    },
    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jquery: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
            moment: 'moment',
            Popper: ['popper.js', 'default']
        }),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        }),
        new ExtractTextPlugin("[name].min.css")
    ],
    module: {
        loaders: [
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-loader?minimize'
                })
            },
            {
                test: /\.(png|woff|woff2|eot|ttf|svg)$/,
                loader: 'url-loader?limit=100000'
            },
            {
                test: require.resolve('jquery'),
                use: [{
                    loader: 'expose-loader',
                    options: 'jQuery'
                },{
                    loader: 'expose-loader',
                    options: '$'
                }]
            }
        ]
    }
};
```
And entry.js file is something like this:
```
global.moment = require('./node_modules/moment');

require('./node_modules/jquery-ui-dist/jquery-ui.min.js');
require('./node_modules/jquery-ajax-native');
import 'bootstrap';
```
After the bundle build I see 'ajax-native' it in the code, but it's "not reachable". Webpack does some changing to scripts so maybe there's a tricky way to import plugin or plugin is not properly optimized, I have no clue at the moment...

**Comment by tarikbenmerar** [comment]
@s0By ok I understand the problem. The plugin for now doesn't return anything. In fact, it just changes the jQuery object. It is just sufficient to use the jQuery module to manipulate the plugin. I can change the plugin so that it returns the jQuery object. Hope, it makes sense.

**Comment by s0By** [comment]
Some workaround would be nice, so it would start working, yes. 
I used bower and grunt before, but bower is slowly dying, browserify and webpack are more common approached now. Adjustments will make the script future-proof for some time. 

Huge fan of this script, especially for blob handling.

**Comment by tarikbenmerar** [comment]
@s0By OK, cool I will push something today and let me know if it works. Can I push in a different branch that you can use it for test ? Also, can you make it work for now ?

Thank you for the encouragement. I am curious about the kind of works you are doing with the library.

**Comment by s0By** [comment]
Sure, test branch is fine. 
At the moment I can make the script work if I include it the old fashioned way (separately from compiled bundle). 

We are developing an EPR system, and the library handles blob download of documents, gallery files, zip archives. Really handy 👍 Documents can be downloaded even without using this library, because technically ajax can handle blob under 10mb (without any extra functionality), but it's pretty useless in our case.

**Comment by tarikbenmerar** [comment]
@s0By hi. Sorry for my late response, being a little bit busy these days. Can you please use the branch and tell me if it works well : https://github.com/acigna/jquery-ajax-native/tree/test/return-jquery-object

**Comment by s0By** [comment]
@tarikbenmerar Hi. Sorry for my absence. Just tested, seems like it works! It would be nice to update it for npm/yarn 👍

**Comment by tarikbenmerar** [comment]
@s0By can you please check on NPM. I have updated it. Thanks for your feedbacks. I am closing the issue.
