### ISSUE TITLE
Working with json errors?

### ISSUE THREAD

**Issue by jcope2013** [acigna/jquery-ajax-native#4]
right now it seems even when I get server errors it goes into the onload callback and not the onerror callback and gets down to this line

https://github.com/acigna/jquery-ajax-native/blob/master/src/jquery-ajax-native.js#L103

my errors ending up being accessible as xhr.response in a json blob so I did something like this, using the fileReader to get the content of the json blob (https://github.com/acigna/jquery-ajax-native/blob/master/src/jquery-ajax-native.js#L100) 

this seems to work, but I was wondering if there is any best practices to handle this?

```
else { 
var isSuccess = xhr.status >= 200 && xhr.status < 300 || xhr.status === 304;

if (isSuccess) {
 if (xhr.response) {
  responses.native = xhr.response;
 }
 complete(
     xhrSuccessStatus[ xhr.status ] || xhr.status,
     xhr.statusText,
     responses,
     xhr.getAllResponseHeaders()
 );
} else {
 // In case an error occured we assume that the response body contains
 // a json blob - so let's convert the binary data to a string which we can
 // pass to the complete callback.

 var fr = new FileReader();
 fr.onload = function() {
   responses.text = this.result;
   complete(
       xhrSuccessStatus[ xhr.status ] || xhr.status,
       xhr.statusText,
       responses,
       xhr.getAllResponseHeaders()
   );
 };

 fr.readAsText(xhr.response, 'utf-8');
} 

```

**Comment by tarikbenmerar** [comment]
@jcope2013 this is strange for me. The error handling in the plugin is identical to the jquery ajax one except there is an added response handling (https://github.com/jquery/jquery/blob/master/src/ajax/xhr.js). Can you please give me the original request you are using ? I want to understand more about the issue. 

Thanks for reporting this.

**Comment by tarikbenmerar** [comment]
@jcope2013 I am closing the issue as I didn't get a reply to my last comment.
