### ISSUE TITLE
jquery 1.11.x cve security vulnerability

### ISSUE THREAD

**Issue by txm** [acigna/jquery-ajax-native#6]
https://www.cvedetails.com/vulnerability-list/vendor_id-6538/Jquery.html

https://github.com/acigna/jquery-ajax-native/pull/5

**Comment by txm** [comment]
Bump :)

**Comment by tarikbenmerar** [comment]
@txm pull request merged. Thanks.

**Comment by tarikbenmerar** [comment]
@txm please upgrade to version 2 of the package on npm to get the security fix. Thanks.
